Day63Demo/Models/ErrorViewModel.cs
namespace Day63Demo.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Day63Demo/Controllers/DepartmentsController.cs
using Microsoft.AspNetCore.Mvc;
using Day63Demo.Data.Services;
using Day63Demo.Data.ViewModels;

namespace Day63Demo.Controllers;

public class DepartmentsController : Controller
{
    private readonly IDepartmentsService _departmentsService;

    public DepartmentsController(IDepartmentsService departmentsService)
    {
        _departmentsService = departmentsService;
    }

    // GET: Departments
    public async Task<IActionResult> Index()
    {
        var departments = await _departmentsService.GetAllAsync();
        return View(departments);

    }

    // GET: Departments/Details/5
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null)
            return NotFound();

        var department = await _departmentsService.GetByIdAsync((int)id);

        if (department == null)
            return NotFound();

        return View(department);
    }

    // GET: Departments/Create
    public IActionResult Create()
    {
        return View();
    }

    // POST: Departments/Create
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(DepartmentViewModel department)
    {
        if (ModelState.IsValid)
        {
            await _departmentsService.CreateAsync(department);
            return RedirectToAction(nameof(Index));
        }

        return View(department);
    }
}

Day63Demo/Controllers/EmployeesController.cs
using Microsoft.AspNetCore.Mvc;
using Day63Demo.Data.Services;
using Day63Demo.Data.ViewModels;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Day63Demo.Controllers;

public class EmployeesController : Controller
{
    private readonly IEmployeesService _employeesService;
    private readonly ILogger<EmployeesController> _logger;

    public EmployeesController(IEmployeesService employeesService, ILogger<EmployeesController> logger)
    {
        _employeesService = employeesService;
        _logger = logger;
    }

    // GET: Employees
    public async Task<IActionResult> Index()
    {
        var employees = await _employeesService.GetAllAsync();
        return View(employees);

    }

    // GET: Employees/Details/5
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null)
            return NotFound();

        var employee = await _employeesService.GetByIdAsync((int)id);

        if (employee == null)
            return NotFound();

        return View(employee);
    }

    // GET: Employees/Create
    public async Task<IActionResult> Create()
    {
        ViewData["DepartmentList"] = await GetSelectListDepartmentAsync();
        ViewData["NationalityList"] = await GetSelectListNationalityAsync();

        return View();
    }

    // POST: Employees/Create
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(EmployeeViewModel employee)
    {
        if (ModelState.IsValid)
        {
            try
            {
                await _employeesService.CreateAsync(employee);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                _logger.LogError(e, "Some Error occurred while creating employee. for employee id = {Name}", employee.Name);

                ModelState.AddModelError(string.Empty, "Cannot create Employee at this time");

                return View(employee);
            }
        }

        ViewData["DepartmentList"] = await GetSelectListDepartmentAsync();
        ViewData["NationalityList"] = await GetSelectListNationalityAsync();

        return View(employee);
    }

    private async Task<SelectList> GetSelectListDepartmentAsync()
    {
        _logger.LogInformation("Started GetSelectListDepartmentAsync");
        return new SelectList(
            await _employeesService.GetDepartmentForDropDownAsync(),
            nameof(DropDownViewModel.Id), nameof(DropDownViewModel.Text));
    }

    private async Task<SelectList> GetSelectListNationalityAsync()
    {
        _logger.LogInformation("Started GetSelectListNationalityAsync");

        return new SelectList(
            await _employeesService.GetNationalityForDropDownAsync(),
            nameof(DropDownViewModel.Id), nameof(DropDownViewModel.Text));
    }
}

Day63Demo/Controllers/HomeController.cs
using Day63Demo.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using AutoMapper;
using Day63Demo.Data;
using Microsoft.EntityFrameworkCore;

namespace Day63Demo.Controllers
{
    public class TestDataModel
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public string Address { get; set; }
        public int Age { get; set; }
    }


    public class TestViewModel
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Telephone { get; set; }
    }


    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IMapper _mapper;
        private readonly ApplicationDbContext _db;

        public HomeController(ILogger<HomeController> logger, IMapper mapper, ApplicationDbContext db)
        {
            _logger = logger;
            _mapper = mapper;
            _db = db;
        }

        public async Task<IActionResult> Index()
        {

            //var testViewModel = testDataModel
            //    .Select(dm => new TestViewModel { FirstName = dm.FirstName, LastName = dm.LastName, Telephone = dm.Telephone })
            //    .ToList();

            var testDataModel = await _db.TestDataModel.ToListAsync();
            var testViewModel2 = testDataModel.Select(dm => _mapper.Map<TestViewModel>(dm)).ToList();

            var testViewModel3 = await _mapper.ProjectTo<TestViewModel>(_db.TestDataModel).ToListAsync();

            return View(testViewModel3);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Day63Demo/Views/Departments/Create.cshtml
@model DepartmentViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Department</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div>
                <label asp-for="Id"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div>
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div>
                <label asp-for="Description"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div>
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Day63Demo/Views/Departments/Details.cshtml
@model DepartmentViewModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Department</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

Day63Demo/Views/Departments/Index.cshtml
@model IEnumerable<DepartmentViewModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                <a asp-action="Details" asp-route-id="@item.Id">Details</a>
            </td>
        </tr>
}
    </tbody>
</table>

Day63Demo/Views/Employees/Create.cshtml
@model EmployeeViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Employee</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div>
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div>
                <label asp-for="DateOfBirth"></label>
                <input asp-for="DateOfBirth" class="form-control" />
                <span asp-validation-for="DateOfBirth" class="text-danger"></span>
            </div>
            <div>
                <label asp-for="Gender"></label>
                <input asp-for="Gender" class="form-control" />
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div>
                <label asp-for="DepartmentRefId"></label>
                <select asp-for="DepartmentRefId" class ="form-control" asp-items="ViewBag.DepartmentList"></select>
                <span asp-validation-for="DepartmentRefId" class="text-danger"></span>
            </div>
            <div>
                <label asp-for="NationalityRefId"></label>
                <select asp-for="NationalityRefId" class ="form-control" asp-items="ViewBag.NationalityList"></select>
                <span asp-validation-for="NationalityRefId" class="text-danger"></span>
            </div>
            <div>
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Day63Demo/Views/Employees/Details.cshtml
@model EmployeeViewModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Employee</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gender)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DepartmentName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DepartmentName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NationalityText)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NationalityText)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

Day63Demo/Views/Employees/Index.cshtml
@model IEnumerable<EmployeeViewModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateOfBirth)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Gender)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DepartmentRefId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DepartmentName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NationalityRefId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NationalityText)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateOfBirth)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gender)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DepartmentRefId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DepartmentName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NationalityRefId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NationalityText)
            </td>
            <td>
                <a asp-action="Details" asp-route-id="@item.Id">Details</a>
            </td>
        </tr>
}
    </tbody>
</table>

Day63Demo/Views/Home/Index.cshtml
@model List<Day63Demo.Controllers.TestViewModel>
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

<table class="table table-bordered">
    <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Telephone</th>
    </tr>
    @foreach (var viewModel in Model)
    {
        <tr>
            <td>@viewModel.FirstName</td>
            <td>@viewModel.LastName</td>
            <td>@viewModel.Telephone</td>
        </tr>
    }
</table>

Day63Demo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Day63Demo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Day63Demo.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Day63Demo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Departments" asp-action="Index">Departments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employees" asp-action="Index">Employees</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Day63Demo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>